Repository ChainSafe/ChainBridge, pull requests merged in 2020-03, with the labels that each got.

#149 Contracts Refactor
  .gitattributes
  .gitignore
  on-chain/evm-contracts/contracts/Bridge.sol
  on-chain/evm-contracts/contracts/BridgeAsset.sol
  on-chain/evm-contracts/contracts/ERC20Safe.sol
  on-chain/evm-contracts/contracts/ERC721Safe.sol
  on-chain/evm-contracts/contracts/Emitter.sol
  on-chain/evm-contracts/contracts/Receiver.sol
  on-chain/evm-contracts/contracts/Safe.sol
  on-chain/evm-contracts/contracts/Validator.sol
  on-chain/evm-contracts/contracts/handlers/ERC20Handler.sol
  on-chain/evm-contracts/contracts/handlers/ERC721Handler.sol
  on-chain/evm-contracts/contracts/handlers/Erc20Handler.sol
  on-chain/evm-contracts/contracts/handlers/Erc721Handler.sol
  on-chain/evm-contracts/contracts/interfaces/IDepositHandler.sol
  on-chain/evm-contracts/contracts/interfaces/IERC20Handler.sol
  on-chain/evm-contracts/contracts/interfaces/IERC721Handler.sol
  on-chain/evm-contracts/contracts/interfaces/IHandler.sol
  on-chain/evm-contracts/contracts/interfaces/ISafe.sol
  on-chain/evm-contracts/contracts/interfaces/IValidator.sol
  on-chain/evm-contracts/contracts/tests/SimpleEmitter.sol
  on-chain/evm-contracts/package-lock.json
  on-chain/evm-contracts/package.json
  on-chain/evm-contracts/test/chainBridge/createDepositProposal.js
  on-chain/evm-contracts/test/chainBridge/depositERC20.js
  on-chain/evm-contracts/test/chainBridge/depositERC721.js
  on-chain/evm-contracts/test/chainBridge/depositGeneric.js
  on-chain/evm-contracts/test/chainBridge/voteDepositProposal.js
Labels: Ethereum

#169 Update go bindings
  .gitignore
  .travis.yml
  Makefile
  chains/ethereum/chain.go
  chains/ethereum/config.go
  chains/ethereum/connection_test.go
  chains/ethereum/contracts.go
  chains/ethereum/events.go
  chains/ethereum/listener.go
  chains/ethereum/listener_test.go
  chains/ethereum/methods.go
  chains/ethereum/writer.go
  chains/ethereum/writer_test.go
  contracts/BridgeAsset/BridgeAsset.go
  contracts/Emitter/Emitter.go
  contracts/Receiver/Receiver.go
  contracts/Safe/Safe.go
  contracts/SimpleEmitter/SimpleEmitter.go
  go.sum
Labels: Ethereum, Priority: 2 - High

#197 Add runtime bytecode to go bindings
  on-chain/evm-contracts/scripts/compileAbiBin.js
  scripts/evm/create_go_bindings.sh
Labels: Ethereum

#144 Voting
  chains/ethereum/chain.go
  chains/ethereum/contracts.go
  chains/ethereum/events.go
  chains/ethereum/listener.go
  chains/ethereum/methods.go
  go.mod
  go.sum
  on-chain/evm-contracts/contracts/Receiver.sol
  on-chain/evm-contracts/scripts/cli/constants.js
  on-chain/evm-contracts/scripts/cli/delpoyment.js
  on-chain/evm-contracts/scripts/cli/transfer.js
  scripts/configs/config.toml
Labels: Ethereum

#199 patch bug
  scripts/evm/create_go_bindings.sh
Labels: Ethereum

#202 Updating KeyRing to use Specfic Keys
  chains/ethereum/connection_test.go
  keystore/keyring.go
Labels: Status: Merge Ready

#214 Keyring bug fixes
  crypto/keypair.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/sr25519.go
  keystore/keyring.go
  keystore/keystore.go
  on-chain/evm-contracts/scripts/cli/constants.js
  scripts/local_test/start_ganache.sh
Labels: Status: Needs Review

#242 Update Solidity version
  .gitignore
  on-chain/evm-contracts/contracts/Bridge.sol
  on-chain/evm-contracts/contracts/BridgeAsset.sol
  on-chain/evm-contracts/contracts/ERC20Safe.sol
  on-chain/evm-contracts/contracts/ERC721Safe.sol
  on-chain/evm-contracts/contracts/Emitter.sol
  on-chain/evm-contracts/contracts/GSN/Context.sol
  on-chain/evm-contracts/contracts/Migrations.sol
  on-chain/evm-contracts/contracts/Receiver.sol
  on-chain/evm-contracts/contracts/Relayer.sol
  on-chain/evm-contracts/contracts/Safe.sol
  on-chain/evm-contracts/contracts/access/Roles.sol
  on-chain/evm-contracts/contracts/access/roles/MinterRole.sol
  on-chain/evm-contracts/contracts/erc/ERC165/ERC165.sol
  on-chain/evm-contracts/contracts/erc/ERC165/IERC165.sol
  on-chain/evm-contracts/contracts/erc/ERC20/ERC20.sol
  on-chain/evm-contracts/contracts/erc/ERC20/ERC20Detailed.sol
  on-chain/evm-contracts/contracts/erc/ERC20/ERC20Mintable.sol
  on-chain/evm-contracts/contracts/erc/ERC20/IERC20.sol
  on-chain/evm-contracts/contracts/erc/ERC721/ERC721.sol
  on-chain/evm-contracts/contracts/erc/ERC721/ERC721Mintable.sol
  on-chain/evm-contracts/contracts/erc/ERC721/IERC721.sol
  on-chain/evm-contracts/contracts/erc/ERC721/IERC721Receiver.sol
  on-chain/evm-contracts/contracts/handlers/ERC20Handler.sol
  on-chain/evm-contracts/contracts/handlers/ERC721Handler.sol
  on-chain/evm-contracts/contracts/helpers/Address.sol
  on-chain/evm-contracts/contracts/helpers/Counters.sol
  on-chain/evm-contracts/contracts/helpers/Ownable.sol
  on-chain/evm-contracts/contracts/helpers/SafeMath.sol
  on-chain/evm-contracts/contracts/interfaces/IDepositHandler.sol
  on-chain/evm-contracts/contracts/interfaces/IERC20Handler.sol
  on-chain/evm-contracts/contracts/interfaces/IERC721Handler.sol
  on-chain/evm-contracts/contracts/interfaces/IHandler.sol
  on-chain/evm-contracts/contracts/interfaces/IRelayer.sol
  on-chain/evm-contracts/contracts/interfaces/ISafe.sol
  on-chain/evm-contracts/contracts/tests/SimpleEmitter.sol
  on-chain/evm-contracts/contracts/tests/SimpleToken.sol
  on-chain/evm-contracts/truffle-config.js
Labels: Status: Merge Ready

#134 Substrate Listener & Writer Pallet Integration
  chains/centrifuge/centrifuge.go
  chains/centrifuge/connection.go
  chains/centrifuge/connection_test.go
  chains/centrifuge/events.go
  chains/centrifuge/listener.go
  chains/centrifuge/writer.go
  chains/interfaces.go
  chains/substrate/chain.go
  chains/substrate/connection.go
  chains/substrate/connection_test.go
  chains/substrate/events.go
  chains/substrate/listener.go
  chains/substrate/methods.go
  chains/substrate/test_helper_test.go
  chains/substrate/types.go
  chains/substrate/writer.go
  chains/substrate/writer_test.go
  cmd/chainbridge/main.go
  go.mod
  go.sum
  message/id.go
  message/message.go
  scripts/centrifuge/ci.sh
  scripts/centrifuge/run_chain.sh
  scripts/centrifuge/run_chain_ci.sh
Labels: Status: Needs Review

#241 Update simulations
  README.md
  on-chain/evm-contracts/scripts/cli/constants.js
  on-chain/evm-contracts/scripts/cli/delpoyment.js
  on-chain/evm-contracts/scripts/cli/index.js
  on-chain/evm-contracts/scripts/cli/transfer.js
  scripts/configs/config1.toml
Labels: Status: Needs Changes

#250 Add Deposit Flow Diagrams
  docs/ChainBridgeV2-ERC20-Deposit-Diagrams.drawio
  docs/ChainBridgeV2-ERC20-Deposit-Picture-Diagram.jpg
  docs/ChainBridgeV2-ERC20-Deposit-Swimlane-Diagram.jpg
Labels: Status: Merge Ready

#246 Fix voting
  chains/ethereum/methods.go
Labels: Ethereum, Status: Needs Review

#248 Add config validation
  README.md
  chains/ethereum/chain.go
  chains/ethereum/config.go
  chains/ethereum/config_test.go
  chains/ethereum/connection.go
  cmd/chainbridge/config.go
  cmd/chainbridge/config_test.go
  cmd/chainbridge/main.go
  core/chain.go
Labels: Status: Needs Review

#167 Silent Fail Bug Fix
  chains/ethereum/chain.go
  chains/ethereum/connection.go
  chains/ethereum/connection_test.go
Labels: Status: Needs Changes

#187 Deploying contracts on local network with go
  cmd/chainbridge/deploycontracts.go
  cmd/chainbridge/flags.go
  cmd/chainbridge/main.go
Labels: Status: Needs Changes

#216 Simplify interfaces
  chains/ethereum/chain.go
  chains/ethereum/connection.go
  chains/ethereum/events.go
  chains/ethereum/listener.go
  chains/interfaces.go
  chains/substrate/events.go
  chains/substrate/listener.go
Labels: Status: Merge Ready

#252 Fixed deprecated signature
  .gitignore
  chains/ethereum/events.go
Labels: Status: Merge Ready

#185 Starting Ganache Eth Chain in Golang
  cmd/chainbridge/deploy.go
  cmd/chainbridge/flags.go
  cmd/chainbridge/main.go
  keystore/keyring.go
Labels: Status: Needs Review

#261 refctor deploy command
  chains/ethereum/deploy.go
  cmd/chainbridge/deployContracts.go
Labels: Priority: 2 - High

#263 Update and rename PR template
  .github/pull_request_template.md
Labels: Status: Needs Review

#235 Adding HTTP Support
  README.md
  chains/ethereum/config.go
  chains/ethereum/config_test.go
  chains/ethereum/connection.go
Labels: Status: Merge Ready

#260 Update How Deposit Proposal Tracks Votes
  chains/ethereum/contracts.go
  on-chain/evm-contracts/contracts/Bridge.sol
  on-chain/evm-contracts/test/chainBridge/createDepositProposal.js
  on-chain/evm-contracts/test/chainBridge/depositGeneric.js
  on-chain/evm-contracts/test/chainBridge/voteDepositProposal.js
Labels: Status: Merge Ready

#266 Updates gsrpc and pallet
  chains/substrate/connection.go
  chains/substrate/connection_test.go
  chains/substrate/listener.go
  chains/substrate/methods.go
  chains/substrate/test_helper_test.go
  chains/substrate/types.go
  chains/substrate/writer.go
  chains/substrate/writer_test.go
  go.mod
  go.sum
  scripts/centrifuge/run_chain_ci.sh
Labels: Status: Needs Review

#270 Fix password bug
  keystore/keystore.go
Labels: Status: Needs Review

#265 Add sr25519 hardcoded keys
  crypto/sr25519/sr25519.go
  keystore/keyring.go
  keystore/keyring_test.go
Labels: Status: Needs Review

#264 Test time!
  chains/ethereum/connection_test.go
  chains/ethereum/contracts.go
  chains/ethereum/deploy.go
  chains/ethereum/listener_test.go
  chains/ethereum/method_test.go
  chains/ethereum/methods.go
  chains/ethereum/writer.go
  chains/ethereum/writer_test.go
Labels: Status: Needs Changes

#269 update contracts
  docs/ChainBridgeV2-ERC20-Deposit-Diagrams-Picture Diagram.jpg
  docs/ChainBridgeV2-ERC20-Deposit-Diagrams.drawio
  docs/ChainBridgeV2-ERC20-Deposit-Picture-Diagram.jpg
Labels: Ethereum, documentation

#215 Implementing Substrate Lock
  chains/substrate/connection.go
  chains/substrate/listener.go
  chains/substrate/writer.go
  chains/substrate/writer_test.go
Labels: Status: Needs Review

#279 Removes v2 suffix
  .golangci.yml
  README.md
  chains/ethereum/chain.go
  chains/ethereum/config.go
  chains/ethereum/config_test.go
  chains/ethereum/connection.go
  chains/ethereum/connection_test.go
  chains/ethereum/deploy.go
  chains/ethereum/events.go
  chains/ethereum/listener.go
  chains/ethereum/listener_test.go
  chains/ethereum/method_test.go
  chains/ethereum/methods.go
  chains/ethereum/writer.go
  chains/ethereum/writer_test.go
  chains/interfaces.go
  chains/substrate/chain.go
  chains/substrate/events.go
  chains/substrate/listener.go
  chains/substrate/types.go
  chains/substrate/writer.go
  chains/substrate/writer_test.go
  cmd/chainbridge/account.go
  cmd/chainbridge/account_test.go
  cmd/chainbridge/config.go
  cmd/chainbridge/deploy.go
  cmd/chainbridge/deployContracts.go
  cmd/chainbridge/main.go
  core/chain.go
  core/core.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/sr25519.go
  go.mod
  go.sum
  keystore/decrypt.go
  keystore/encrypt.go
  keystore/encrypt_test.go
  keystore/keyring.go
  keystore/keystore.go
  router/router.go
  router/router_test.go
  scripts/docker/start-docker.sh
Labels: Status: Needs Review

#280 Adds implementation section to readme
  README.md
Labels: Status: Needs Review

#274 Substrate listener tests
  .travis.yml
  README.md
  chains/ethereum/chain.go
  chains/ethereum/methods.go
  chains/substrate/chain.go
  chains/substrate/config.go
  chains/substrate/config_test.go
  chains/substrate/connection.go
  chains/substrate/connection_test.go
  chains/substrate/events.go
  chains/substrate/listener.go
  chains/substrate/listener_test.go
  chains/substrate/methods.go
  chains/substrate/test_helper_test.go
  chains/substrate/types.go
  chains/substrate/writer_test.go
  core/chain.go
  core/core.go
  go.mod
  go.sum
  scripts/substrate/run_chain_ci.sh
Labels: Status: Needs Review

#262 Importing Geth Keystore Files
  README.md
  cmd/chainbridge/account.go
  cmd/chainbridge/flags.go
  cmd/chainbridge/main.go
  go.sum
Labels: Status: Needs Review

#278 Greg/listener/tests
  chains/ethereum/connection_test.go
  chains/ethereum/contracts.go
  chains/ethereum/deploy.go
  chains/ethereum/deposit_test.go
  chains/ethereum/listener_test.go
  chains/ethereum/method_test.go
  go.sum
Labels: Ethereum, Priority: 2 - High, Status: Needs Review

#273 Updating Logging
  chains/ethereum/chain.go
  chains/ethereum/connection.go
  chains/ethereum/connection_test.go
  chains/ethereum/events.go
  chains/ethereum/listener.go
  chains/ethereum/listener_test.go
  chains/ethereum/method_test.go
  chains/ethereum/methods.go
  chains/ethereum/writer.go
  chains/ethereum/writer_test.go
  chains/substrate/chain.go
  chains/substrate/connection.go
  chains/substrate/connection_test.go
  chains/substrate/events.go
  chains/substrate/listener.go
  chains/substrate/listener_test.go
  chains/substrate/test_helper_test.go
  chains/substrate/writer.go
  chains/substrate/writer_test.go
  message/id.go
  router/router_test.go
Labels: Status: Merge Ready
